import type {
  DailySummary,
  MemberSubscriptionRecord,
  MockChartOfAccount,
  MockExpenseAccount,
  MockPendingUser,
  Product,
  Role,
  UserSession,
} from "@/lib/contracts";

export const demoPassword = "demo1234";

export const mockUsersByRole: Record<Role, UserSession> = {
  OWNER: {
    user_id: 1,
    username: "owner",
    full_name: "Lalin Charoen",
    role: "OWNER",
    active_shift_id: null,
  },
  ADMIN: {
    user_id: 2,
    username: "admin",
    full_name: "Niran Ops Lead",
    role: "ADMIN",
    active_shift_id: null,
  },
  CASHIER: {
    user_id: 3,
    username: "cashier",
    full_name: "Pim Counter",
    role: "CASHIER",
    active_shift_id: null,
  },
};

export const mockProducts: Product[] = [
  {
    product_id: 101,
    sku: "WATER-01",
    name: "Mineral Water",
    price: 25,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 18,
  },
  {
    product_id: 102,
    sku: "COFFEE-01",
    name: "Iced Americano",
    price: 50,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 20,
  },
  {
    product_id: 103,
    sku: "SHAKE-01",
    name: "Protein Shake",
    price: 95,
    product_type: "GOODS",
    track_stock: true,
    stock_on_hand: 6,
  },
  {
    product_id: 104,
    sku: "DAYPASS",
    name: "Daily Pass",
    price: 80,
    product_type: "MEMBERSHIP",
    revenue_account_id: 10,
    membership_period: "DAILY",
    membership_duration_days: 1,
  },
  {
    product_id: 105,
    sku: "MEM-MONTH",
    name: "Monthly Membership",
    price: 1500,
    product_type: "MEMBERSHIP",
    revenue_account_id: 10,
    membership_period: "MONTHLY",
    membership_duration_days: 30,
  },
  {
    product_id: 106,
    sku: "MEM-3MONTH",
    name: "3-Month Membership",
    price: 3900,
    product_type: "MEMBERSHIP",
    revenue_account_id: 10,
    membership_period: "QUARTERLY",
    membership_duration_days: 90,
  },
  {
    product_id: 107,
    sku: "MEM-6MONTH",
    name: "6-Month Membership",
    price: 7500,
    product_type: "MEMBERSHIP",
    revenue_account_id: 10,
    membership_period: "SEMIANNUAL",
    membership_duration_days: 180,
  },
  {
    product_id: 108,
    sku: "PT-01",
    name: "Personal Training Session",
    price: 500,
    product_type: "SERVICE",
    revenue_account_id: 7,
  },
  {
    product_id: 109,
    sku: "TOWEL-01",
    name: "Towel Service",
    price: 40,
    product_type: "SERVICE",
    revenue_account_id: 7,
  },
  {
    product_id: 110,
    sku: "MEM-YEAR",
    name: "Yearly Membership",
    price: 9900,
    product_type: "MEMBERSHIP",
    revenue_account_id: 10,
    membership_period: "YEARLY",
    membership_duration_days: 365,
  },
  {
    product_id: 111,
    sku: "COFFEE-11",
    name: "Americano Hot",
    price: 45,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 20,
  },
  {
    product_id: 112,
    sku: "COFFEE-12",
    name: "Espresso Hot",
    price: 55,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 18,
  },
  {
    product_id: 113,
    sku: "COFFEE-13",
    name: "Espresso Cold",
    price: 60,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 18,
  },
  {
    product_id: 114,
    sku: "COFFEE-14",
    name: "Latte Hot",
    price: 55,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 16,
  },
  {
    product_id: 115,
    sku: "COFFEE-15",
    name: "Latte Cold",
    price: 60,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 16,
  },
  {
    product_id: 116,
    sku: "COFFEE-16",
    name: "Cappuccino Hot",
    price: 60,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 16,
  },
  {
    product_id: 117,
    sku: "COFFEE-17",
    name: "Cappuccino Cold",
    price: 65,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 16,
  },
  {
    product_id: 118,
    sku: "COFFEE-18",
    name: "Americano Coconut",
    price: 100,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 10,
  },
  {
    product_id: 119,
    sku: "COFFEE-19",
    name: "Latte Oreo",
    price: 75,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 10,
  },
  {
    product_id: 120,
    sku: "COFFEE-20",
    name: "Honey Milk Hot",
    price: 45,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 12,
  },
  {
    product_id: 121,
    sku: "COFFEE-21",
    name: "Honey Milk Cold",
    price: 50,
    product_type: "GOODS",
    revenue_account_id: 6,
    track_stock: true,
    stock_on_hand: 12,
  },
  {
    product_id: 122,
    sku: "FOOD-01",
    name: "Pad Kra Pao Pork + Fried Egg",
    price: 70,
    product_type: "GOODS",
    revenue_account_id: 9,
    track_stock: true,
    stock_on_hand: 12,
  },
  {
    product_id: 123,
    sku: "FOOD-02",
    name: "Pad See Ew Pork",
    price: 70,
    product_type: "GOODS",
    revenue_account_id: 9,
    track_stock: true,
    stock_on_hand: 10,
  },
  {
    product_id: 124,
    sku: "FOOD-03",
    name: "Fried Rice Chicken",
    price: 70,
    product_type: "GOODS",
    revenue_account_id: 9,
    track_stock: true,
    stock_on_hand: 10,
  },
  {
    product_id: 125,
    sku: "FOOD-04",
    name: "Garlic Pork + Fried Egg",
    price: 70,
    product_type: "GOODS",
    revenue_account_id: 9,
    track_stock: true,
    stock_on_hand: 10,
  },
  {
    product_id: 126,
    sku: "FOOD-05",
    name: "Kale Crispy Pork",
    price: 70,
    product_type: "GOODS",
    revenue_account_id: 9,
    track_stock: true,
    stock_on_hand: 10,
  },
  {
    product_id: 127,
    sku: "PT-10",
    name: "PT 10 Sessions",
    price: 4500,
    product_type: "SERVICE",
    revenue_account_id: 7,
  },
  {
    product_id: 128,
    sku: "PT-20",
    name: "PT 20 Sessions",
    price: 8000,
    product_type: "SERVICE",
    revenue_account_id: 7,
  },
  {
    product_id: 129,
    sku: "PT-MONTH",
    name: "PT Monthly Unlimited",
    price: 7000,
    product_type: "SERVICE",
    revenue_account_id: 7,
  },
  {
    product_id: 130,
    sku: "PT-COUPLE",
    name: "PT Couple Monthly",
    price: 12900,
    product_type: "SERVICE",
    revenue_account_id: 7,
  },
];

export const mockMemberSubscriptions: MemberSubscriptionRecord[] = [
  {
    member_id: "MEM-0001",
    member_code: "MBR-24001",
    full_name: "Anan Wattanakul",
    phone: "081-222-4455",
    membership_product_id: 105,
    membership_name: "Monthly Membership",
    membership_period: "MONTHLY",
    started_at: "2026-02-10T09:05:00.000Z",
    expires_at: "2026-03-12T23:59:59.000Z",
    checked_in_at: "2026-03-10T07:10:00.000Z",
    renewed_at: null,
    renewal_status: "ACTIVE",
  },
  {
    member_id: "MEM-0002",
    member_code: "MBR-24002",
    full_name: "Ploy Srisuk",
    phone: "089-454-1188",
    membership_product_id: 104,
    membership_name: "Daily Pass",
    membership_period: "DAILY",
    started_at: "2026-03-10T08:30:00.000Z",
    expires_at: "2026-03-10T23:59:59.000Z",
    checked_in_at: "2026-03-10T08:35:00.000Z",
    renewed_at: null,
    renewal_status: "EXPIRES_TODAY",
  },
  {
    member_id: "MEM-0003",
    member_code: "MBR-24003",
    full_name: "Thanawat Khem",
    phone: "094-882-1109",
    membership_product_id: 110,
    membership_name: "Yearly Membership",
    membership_period: "YEARLY",
    started_at: "2025-03-09T11:00:00.000Z",
    expires_at: "2026-03-09T23:59:59.000Z",
    checked_in_at: "2026-03-08T18:20:00.000Z",
    renewed_at: null,
    renewal_status: "EXPIRED_NOT_RENEWED",
  },
  {
    member_id: "MEM-0004",
    member_code: "MBR-24004",
    full_name: "Mali Prasert",
    phone: "082-991-5500",
    membership_product_id: 105,
    membership_name: "Monthly Membership",
    membership_period: "MONTHLY",
    started_at: "2026-02-09T15:40:00.000Z",
    expires_at: "2026-03-09T23:59:59.000Z",
    checked_in_at: "2026-03-09T19:15:00.000Z",
    renewed_at: "2026-03-10T09:00:00.000Z",
    renewal_status: "RENEWED",
  },
];

export const mockExpenseAccounts: MockExpenseAccount[] = [
  { account_id: 201, account_code: "5201", account_name: "Cleaning Supplies" },
  { account_id: 202, account_code: "5202", account_name: "Small Equipment" },
  { account_id: 203, account_code: "5203", account_name: "Office Snacks" },
  { account_id: 204, account_code: "5204", account_name: "Maintenance Expense" },
];

export const mockChartOfAccounts: MockChartOfAccount[] = [
  {
    account_id: 1,
    account_code: "1111",
    account_name: "Cash on Hand",
    account_type: "ASSET",
    is_active: true,
    description: "บัญชีเงินสดประจำลิ้นชักสำหรับการเปิดกะ ขายหน้าร้าน และปิดกะประจำวัน",
    locked_reason: "บัญชีนี้ถูกอ้างอิงในขั้นตอนเปิดกะและกระทบยอดปิดกะ จึงไม่สามารถปิดใช้งานได้",
  },
  {
    account_id: 2,
    account_code: "1120",
    account_name: "PromptPay Clearing",
    account_type: "ASSET",
    is_active: true,
    description: "ใช้พักยอดรับชำระจาก PromptPay ระหว่างรอการยืนยันและกระทบยอดเข้าบัญชีหลัก",
  },
  {
    account_id: 3,
    account_code: "1130",
    account_name: "Credit Card Receivable",
    account_type: "ASSET",
    is_active: true,
    description: "บันทึกลูกหนี้จากบัตรเครดิตก่อนผู้ให้บริการโอนเงินเข้าบัญชีร้าน",
  },
  {
    account_id: 4,
    account_code: "4010",
    account_name: "Sales Revenue",
    account_type: "REVENUE",
    is_active: true,
    description: "บัญชีรายได้หลักสำหรับสินค้าหรือบริการที่ยังไม่ได้ผูก mapping เฉพาะ",
  },
  {
    account_id: 6,
    account_code: "4101",
    account_name: "Beverage Revenue",
    account_type: "REVENUE",
    is_active: true,
    description: "ใช้บันทึกรายได้จากเครื่องดื่มและสินค้าหน้าร้านที่ต้องการแยกหมวดรายได้",
  },
  {
    account_id: 7,
    account_code: "4102",
    account_name: "Service Revenue",
    account_type: "REVENUE",
    is_active: true,
    description: "ใช้บันทึกรายได้จากบริการ เช่น เทรนเนอร์ส่วนตัว หรือบริการเสริม",
  },
  {
    account_id: 8,
    account_code: "4103",
    account_name: "Membership Revenue",
    account_type: "REVENUE",
    is_active: false,
    description: "บัญชีรายได้สมาชิกเวอร์ชันเก่าที่เก็บไว้เพื่ออ้างอิงย้อนหลัง",
  },
  {
    account_id: 9,
    account_code: "4104",
    account_name: "Food Revenue",
    account_type: "REVENUE",
    is_active: true,
    description: "ใช้บันทึกรายได้จากอาหารตามสั่งและเมนูครัวหน้าร้าน",
  },
  {
    account_id: 10,
    account_code: "4105",
    account_name: "Active Membership Revenue",
    account_type: "REVENUE",
    is_active: true,
    description: "ใช้บันทึกรายได้ค่าสมาชิกตามราคาโปรโมชั่นปัจจุบันของยิม",
  },
  {
    account_id: 5,
    account_code: "5201",
    account_name: "Cleaning Supplies",
    account_type: "EXPENSE",
    is_active: false,
    description: "หมวดค่าใช้จ่ายอุปกรณ์ทำความสะอาดที่เก็บไว้เพื่ออ้างอิงประวัติการตรวจสอบย้อนหลัง",
    locked_reason: "เคยถูกใช้งานในประวัติเงินสดย่อย จึงยังต้องคงไว้สำหรับการตรวจสอบ",
  },
];

export const mockPendingUsers: MockPendingUser[] = [
  {
    request_id: 9001,
    full_name: "Mali Counter",
    username: "mali.counter",
    role: "CASHIER",
    branch_label: "Front Desk",
    status: "PENDING",
    submitted_at: "2026-03-08T08:30:00.000Z",
  },
  {
    request_id: 9002,
    full_name: "Ton Supervisor",
    username: "ton.supervisor",
    role: "ADMIN",
    branch_label: "Main Floor",
    status: "APPROVED",
    submitted_at: "2026-03-07T16:10:00.000Z",
  },
];

export const mockDailySummary: DailySummary = {
  total_sales: 8420,
  sales_by_method: {
    CASH: 3120,
    PROMPTPAY: 2580,
    CREDIT_CARD: 2720,
  },
  total_expenses: 640,
  net_cash_flow: 2480,
  shift_discrepancies: -60,
};