export const productDisplayLabelBySku = {
    "WATER-01": { title: "น้ำดื่ม", subtitle: "ขวดเล็กแช่เย็น" },
    "COFFEE-01": { title: "อเมริกาโน่เย็น", subtitle: "สูตรเข้มตามป้ายร้าน" },
    "COFFEE-02": { title: "อเมริกาโน่เย็น", subtitle: "คั่วกลาง" },
    "COFFEE-03": { title: "อเมริกาโน่เย็น", subtitle: "คั่วอ่อน" },
    "SHAKE-01": { title: "โปรตีนเชค", subtitle: "เครื่องดื่มโปรตีนพร้อมขาย" },
    DAYPASS: { title: "สมาชิกรายวัน", subtitle: "เข้าใช้ได้ 1 วัน" },
    "MEM-MONTH": { title: "สมาชิกรายเดือน", subtitle: "เข้าใช้ได้ 30 วัน" },
    "MEM-3MONTH": { title: "สมาชิก 3 เดือน", subtitle: "แพ็กเกจยอดนิยม" },
    "MEM-6MONTH": { title: "สมาชิก 6 เดือน", subtitle: "แพ็กเกจคุ้มค่าสำหรับลูกค้าประจำ" },
    "MEM-YEAR": { title: "สมาชิกรายปี", subtitle: "เหมาะสำหรับลูกค้าระยะยาว" },
    "SAUNA-01": { title: "ซาวน่า", subtitle: "ค่าบริการ 100 บาท" },
    "PT-01": { title: "เทรนเดี่ยว 1 ครั้ง", subtitle: "ครั้งละ 500 บาท" },
    "PT-10": { title: "เทรน 10 ครั้ง", subtitle: "อายุเทรน 30 วัน" },
    "PT-20": { title: "เทรน 20 ครั้ง", subtitle: "อายุเทรน 60 วัน" },
    "PT-MONTH": { title: "เทรนรายเดือน", subtitle: "ไม่จำกัดครั้ง" },
    "PT-COUPLE": { title: "เทรนคู่รายเดือน", subtitle: "ไม่จำกัดครั้ง" },
    "TOWEL-01": { title: "บริการผ้าเช็ดตัว", subtitle: "บริการเสริมหน้าเคาน์เตอร์" },
    "COFFEE-11": { title: "อเมริกาโน่ร้อน", subtitle: "คั่วเข้ม" },
    "COFFEE-22": { title: "อเมริกาโน่ร้อน", subtitle: "คั่วกลาง" },
    "COFFEE-23": { title: "อเมริกาโน่ร้อน", subtitle: "คั่วอ่อน" },
    "COFFEE-12": { title: "เอสเปรสโซ่ร้อน", subtitle: "ช็อตเข้ม" },
    "COFFEE-13": { title: "เอสเปรสโซ่เย็น", subtitle: "เข้มและหอม" },
    "COFFEE-14": { title: "ลาเต้ร้อน", subtitle: "นมนุ่ม ดื่มง่าย" },
    "COFFEE-15": { title: "ลาเต้เย็น", subtitle: "รสนุ่มตามป้าย" },
    "COFFEE-16": { title: "คาปูชิโน่ร้อน", subtitle: "ฟองนมนุ่ม" },
    "COFFEE-17": { title: "คาปูชิโน่เย็น", subtitle: "เข้มขึ้น หวานน้อย" },
    "COFFEE-18": { title: "อเมริกาโน่มะพร้าว", subtitle: "เมนูพิเศษเย็น" },
    "COFFEE-19": { title: "ลาเต้โอรีโอ้", subtitle: "เมนูหวานขายดี" },
    "COFFEE-20": { title: "ฮันนี่มิลค์ร้อน", subtitle: "นมหอมน้ำผึ้ง" },
    "COFFEE-21": { title: "ฮันนี่มิลค์เย็น", subtitle: "ดื่มง่าย สดชื่น" },
    "COFFEE-24": { title: "เพิ่มเมล็ดคั่วอ่อน", subtitle: "+10 บาท" },
    "COFFEE-25": { title: "เพิ่มน้ำผึ้ง", subtitle: "+10 บาท" },
    "FOOD-01": { title: "กะเพราหมูสับไข่ดาว", subtitle: "จานด่วน 70 บาท" },
    "FOOD-02": { title: "กะเพราไก่ไข่ดาว", subtitle: "จานด่วน 70 บาท" },
    "FOOD-03": { title: "ข้าวลาบหมูไข่ดาว", subtitle: "เมนูขายประจำ" },
    "FOOD-04": { title: "ข้าวลาบไก่ไข่ดาว", subtitle: "เมนูขายประจำ" },
    "FOOD-05": { title: "ข้าวผัดหมูไข่ดาว", subtitle: "จานเดียวพร้อมขาย" },
} as const;
